### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/devel_subthemer#1]
@docwilmot - I would like to start by thanking you, I think that this could be a very valuable module. I would love to see this in core OR a simple version of this made that contrib theme developers could include in their themes. 

I think it would be great if there were a "create subtheme" tab on the settings page for every theme - or if it was easy for theme developers to simply drop this code into their theme and provide this functionality.

Here is my general feedback. 

1) I didn't enable the devel module, so it just shows up in the main admin menu looking a bit out of place. This is not a serious problem and may be resolved by your longer term plans for this module. 

![Screenshot from 2021-11-20 02-31-41](https://user-images.githubusercontent.com/3144571/142719939-c7936e69-0087-4ccd-91d5-dcd9a8648444.png)

2) I would like a little more help text to help new folks better understand the settings. I may write a PR with some ideas. 

3) I think that there should be a default value of `css/custom.css` in the Add Stylesheet Paths field. I think that a new themer might forget to do this and having this default there would help them a lot. Easier to delete it if they don't need it than to add it themselves later.

**Comment by docwilmot** [comment]
> I think it would be great if there were a "create subtheme" tab on the settings page for every theme

I've added a "Create subtheme" link next to every enabled theme on the `admin/appearance` page, that links to the form and preselects that theme.

Fixed the Admin bar link location to `config/development` instead of `devel`.

And I've merged in your PRs, though some modification was done to the help text. Thanks a lot.

**Comment by stpaultim** [comment]
@docwilmot - Not going to reopen this issue, but wanted to update my feedback regarding the longer term future of this module. 

I think that what you have done with the create sub-themes link is a great step forward. I'm revising my opinion on whether or not this belongs in core. I'm not against that, but I think adding it to the devel module might be just as good. 

I'm concerned that as a stand alone module new users might not find it or be aware of it, but that problem can be solved in a variety of ways. I plan to create a screencast to help with that effort. 

Anyone that is going to start creating sub-themes probably ought to be aware of the devel module - if not, we should keep promoting that option as well. I just think that if we're going to point beginner themers at contrib modules, the fewer we have to point them at the better. 

BUT, all of this can be discussed another day. The first important step was creating this module and I'm quite excited about it. I'd rather declare victory and save the next steps discussion for later.

**Comment by docwilmot** [comment]
As far as including this in core, I think it's a dev tool and belongs in contrib TBH, at least until it is well tested. 
And naming it "devel_” to make it discoverable in searches is the best I can do as far as adding it to that module; it's up to the Devel maintainers to decide if it would become part of Devel.
