### ISSUE TITLE
Rename base_theme_wrapper_change_callback to something like refresh_base_theme_options

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel_subthemer#14]
...or something that is more intuitive/self-explanatory. Then also rename the `$form['base_theme_wrapper']*` form elements accordingly, like `$form['base_theme_options']*` or something.

**Comment by docwilmot** [comment]
Well... not so sure. That element is the wrapper for the base theme select, hence `base_theme_wrapper`, and because its AJAXified, it has a callback, hence `base_theme_wrapper_change_callback`. I think thats actually more explanatory.

**Comment by klonos** [comment]
Perhaps I need to better wrap my head around the way AJAXified forms work, and the terminology around them.
