### ISSUE TITLE
Suggestion for the help text.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel_subthemer#17]
I believe that the help text at the top of the form could be improved.

Current:
> Completing this form will generate a subtheme file in your themes directory. For more information see our documentation on [creating a subtheme.](https://docs.backdropcms.org/documentation/creating-sub-themes)

Proposed change:

> This form automates the initial creation of a subtheme. A new folder will be created in your themes directory, with all the necessary files (according to selected options below). For more information, see the documentation on [creating a subtheme](https://docs.backdropcms.org/documentation/creating-sub-themes).

**Comment by klonos** [comment]
@stpaultim thoughts on this please?

**Comment by stpaultim** [comment]
I think that this is an improvement. I created my text as a first draft and hoped that others would offer improvements, I think that @klonos has done that. 

Merge away @docwilmot
