### ISSUE TITLE
Sanitize file paths provided by users

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/devel_subthemer#23]
Re that todo: https://github.com/backdrop-contrib/devel_subthemer/blob/1.x-1.x/devel_subthemer.module#L199

Here's a (sort of) paranoid function:

```php
/**
 * Sanitize user provided paths.
 *
 * @param string $string
 *   Provided path.
 * @param string $extension
 *   Extension excluding the dot, like "css" or "js".
 *
 * @return string
 *   Sanitized string.
 */
function devel_subthemer_sanitize_path($string, $extension) {
  // White space around.
  $string = trim($string);
  // Double dot - would leave directory.
  $string = str_replace('..', '', $string);
  // Multiple consecutive slashes, might be caused by the previous check.
  $string = preg_replace('!/+!', '/', $string);
  // Any characters not suitable for asset paths.
  $string = preg_replace(':[^a-zA-Z0-9/_\.-]:', '-', $string);
  // Leading dot, harmless but not necessary.
  $string = preg_replace(':^\.:', '', $string);
  // Leading and ending slash.
  $string = trim($string, '/');
  // Add extension if needed.
  $ext = explode('.', $string);
  if (end($ext) != $extension) {
    $string .= '.' . $extension;
  }
  return $string;
}
```
This is by intention no PR, as you might not want all of those checks. :wink: Just pick what seems appropriate.

Here's a list of odd paths to play with:
```
$odd = array(
  'bla/../../foo.css',
  '../bar',
  ' what the space.css',
  'odd%20{}chars#[]within',
  './bar/baz/boo',
  'foobar.php',
  '/path/to/thing.inc',
);

```
I did a quick check, BTW, yes a path like `../css/custom.css` does currently create that css directory outside the subtheme's path.

**Comment by docwilmot** [comment]
Ahh again, I created a repo and didnt subscribe to it. Didnt see your issue, sorry @indigoxela. Just pushed a validation commit. I opted to just throw an error if there is a dot rather than trying to rewrite it for the user. Thanks anyway

**Comment by indigoxela** [comment]
> opted to just throw an error if there is a dot rather than trying to rewrite it for the user.

Sure, no problem. :wink: I think, we can close this issue now.
