### ISSUE TITLE
Added stylesheets and scripts are containing an addional css extension

### ISSUE THREAD

**Issue by schoenid** [backdrop-contrib/devel_subthemer#28]
Adding styleshees and scripts works, but the files are containing an additional .css extension.

### Add stylesheet paths

`css/custom.css` --> css/custom.css.css

### Add script paths

`js/custom.js` --> js/custom.js.css

### File: <templatename>.info

    name =<templatename>
    description = Subtheme of Basis
    type = theme
    backdrop = 1.x
    base theme = basis
    
    stylesheets[all][] = css/custom.css.css
    stylesheets[all][] = css/colors.css
    
    scripts[] = js/custom.js.css

Backdrop 1.21.4
Plugin installed by Plugin manager `/admin/modules/install`

Sure I can correct the file names and the info entry manually. It is not comfortable.

Anyway, I'm happy to have this tool.

**Comment by docwilmot** [comment]
Thanks, this was fixed but I forgot to push new release. Latest code should not create this error.
