### ISSUE TITLE
Menu item position, config path, button text

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/devel_subthemer#6]
First of all: great module! :rocket:

Some suggestions:

Currently the menu item position in the admin menu is odd. When devel isn't installed, it ends up top level. I'd rather expect it to be somewhere under "Appearance".

And the configure path is still commented in the info file, so the link doesn't appear in the module listing.

The form submit button text "Convert files" seems a bit odd. Shouldn't that be "Create subtheme"?

**Comment by docwilmot** [comment]
I've change to just use `admin/config/development/devel-subthemer` and forget Devel. All issues fixed then.

**Comment by docwilmot** [comment]
> First of all: great module! 🚀

Thanks.
