### ISSUE TITLE
What to do with the form after intial creation

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/devel_subthemer#7]
Creating subthemes works great!

But how should this module handle things after the subtheme has been created. The form is still available - with the values provided (by browser), but trying to hit the submit button again produces a form error regarding machine name in use.

Should this module keep track of created subtheme in any way? If not, at least a form redirect after successful submission might make sense. For instance to the theme listing page?

**Comment by docwilmot** [comment]
Thanks, I've added a redirect to the themes listing page. Hope thats acceptable.
